steps:
  - id: build
    name: 'gcr.io/kaniko-project/executor:v0.16.0'
    args:
      - --dockerfile=./Dockerfile
      - --destination=gcr.io/${PROJECT_ID}/${_APP_NAME}
      - --cache=true
      - --cache-ttl=6h
  - id: "deploy"
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud beta run deploy ${_APP_NAME} \
          --platform managed \
          --region asia-northeast1 \
          --allow-unauthenticated \
          --image gcr.io/${PROJECT_ID}/${_APP_NAME} \
substitutions:
  _APP_NAME: puppeteer-demo
